<?php
if (!defined("INSIDE")){die("Hacking attempt");}
$wg_village_kinds=array();
$wg_village_kinds[0]['id']=1;
$wg_village_kinds[0]['image']='f1';
$wg_village_kinds[1]['id']=2;
$wg_village_kinds[1]['image']='f2';
$wg_village_kinds[2]['id']=3;
$wg_village_kinds[2]['image']='f3';
$wg_village_kinds[3]['id']=4;
$wg_village_kinds[3]['image']='f4';
$wg_village_kinds[4]['id']=5;
$wg_village_kinds[4]['image']='f5';
$wg_village_kinds[5]['id']=6;
$wg_village_kinds[5]['image']='f6';

/*Oasis*/
$wg_village_kinds[6]['id']=7;
$wg_village_kinds[6]['image']='images/un/m/w1.png';
$wg_village_kinds[7]['id']=8;
$wg_village_kinds[7]['image']='images/un/m/w3.png';
$wg_village_kinds[8]['id']=9;
$wg_village_kinds[8]['image']='images/un/m/w4.png';
$wg_village_kinds[9]['id']=10;
$wg_village_kinds[9]['image']='images/un/m/w6.png';
$wg_village_kinds[10]['id']=11;
$wg_village_kinds[10]['image']='images/un/m/w7.png';
$wg_village_kinds[11]['id']=12;
$wg_village_kinds[11]['image']='images/un/m/w9.png';
$wg_village_kinds[12]['id']=13;
$wg_village_kinds[12]['image']='images/un/m/w10.png';
$wg_village_kinds[13]['id']=14;
$wg_village_kinds[13]['image']='images/un/m/w12.png';
?>